### PR TITLE
fix: apply zoomMarkers on first render

### LINKED ISSUE #466: 🐞 showAllMarkers doesn't apply on startup
### Check for existing bug reports before submitting.

- [x] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

When I set `setAllMarkers: true` in a basic configuration, the zoom level should be set to the appropriate value to show all markers on the page.

### Current behaviour

The setting doesn't apply. The zoom level is always set to 1, which is not accurate based on the markers in my example below.

### Reproduction

1. Launch Obsidian Sandbox via the `Open Sandbox Vault` command.
2. Install the Leaflet plugin
3. Place the following leaflet code into a document
```
```leaflet
id: index-peaks
height: 500px
showAllMarkers: true
marker:
  - default, 50.79106, -115.30077, [[places/one.md|One]]
  - default, 51.0633532, -115.440635, [[places/two.md|Two]]

```#
```

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [x] macOS
- [ ] Windows

### Obsidian Version Check

1.9.2 and 1.8.10

### Plugin Version

6.0.5

### Confirmation

- [x] I have disabled all other plugins and the issue still persists.

### Possible solution

Hitting the "show all markers" button on the UI works correctly. It seems like the map hasn't finished initialization/rendering prior to `zoomAllMarkers` being called. Using the debugger and calling `this.leafletInstance.getBounds()` and `this.leafletInstance.getSize()` while inside of `zoomAllMarkers` shows that the instance has a size of zero, which prevents it from calculating the zoom level correctly.

It seems tome like the `zoomAllMarkers` call should be deferred until the Leaflet "load" event triggers.

### PR DESCRIPTION
**Pull request by alaycock**
## Pull Request Description
`zoomMarkers` doesn't apply when first rendering the map. The zoom level is being calculated before the map's initial, which results in it defaulting to `1`.

## Changes Proposed
Wait until the map is fully rendered before applying the `zoomMarkers` configuration option.

## Related Issues

Fixes #466 

## Checklist

- [x] I have read the contribution guidelines and code of conduct.
- [x] I have tested the changes locally and they are working as expected.
- [x] I have added appropriate comments and documentation for the code changes.
- [x] My code follows the coding style and standards of this project.
- [x] I have rebased my branch on the latest main (or master) branch.
- [x] All tests (if applicable) have passed successfully.
- [x] I have run linters and fixed any issues.
- [x] I have checked for any potential security issues or vulnerabilities.

## Screenshots (if applicable)

Before
image

After:
image

### CODE REVIEW

File: src/map/map.ts [hunk 1]
```diff
@@ -214,6 +214,12 @@ export abstract class BaseMap extends Events implements BaseMapDefinition {
         this.leafletInstance.on("click", (evt: L.LeafletMouseEvent) =>
             this.handleMapClick(evt)
         );
+        this.on('rendered', () => {
+            if (this.options.zoomMarkers) {
+                this.log(`Zooming to markers.`);
+                this.zoomAllMarkers();
+            }
+        })
```
Comment (alaycock) [inline src/map/map.ts:222]: This could also live inside of the `render` function, but this felt like a more appropriate place, alongside the other event handlers. I don't see where the `rendered` event is used elsewhere, so if you intended this event to be a external-facing and stable, I could relocate this.
